# Generated by Django 4.1.6 on 2023-02-03 09:18

from django.db import migrations, models
import django.db.models.deletion

# python manage.py makemigrations polls を実行することで、
# Djangoにモデルに変更があったことを伝え、そして変更を マイグレーション の形で保存する。
# このファイルでmigrateを実行したらどうなるかを確認するには、`python manage.py sqlmigrate polls 0001`
# (sqlmigrate コマンドは実際にはデータベースにマイグレーションを実行しない。ただ、Djangoが必要としているSQLが何であるかをスクリーンに表示するだけ。これはDjangoが何をしようとしているかを確認したり、データベース管理者に変更のためのSQLスクリプトを要求されているときに役に立つ。)
# 実際にマイグレーションする場合は、`python manage.py migrate`
class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question_text", models.CharField(max_length=200)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("choice_text", models.CharField(max_length=200)),
                ("votes", models.IntegerField(default=0)),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="polls.question")),
            ],
        ),
    ]
